CREATE TABLE IF NOT EXISTS REQUEST(
  ID BIGSERIAL PRIMARY KEY,
  MESSAGE VARCHAR(300),
  VOICE_TYPE VARCHAR(100),
  REQUESTER VARCHAR(100),
  SUBMITTER VARCHAR(100),
  STATUS VARCHAR(100),
  DATE_OF_CREATION TIMESTAMP
);